CREATE TABLE Books (
    BookID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Author TEXT NOT NULL,
    Genre TEXT,
    PublishedYear INTEGER,
    AvailableCopies INTEGER DEFAULT 1
);

CREATE TABLE Members (
    MemberID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    Phone TEXT,
    JoinDate TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Transactions (
    TransactionID INTEGER PRIMARY KEY AUTOINCREMENT,
    BookID INTEGER NOT NULL,
    MemberID INTEGER NOT NULL,
    BorrowDate TEXT DEFAULT CURRENT_TIMESTAMP,
    ReturnDate TEXT,
    Status TEXT CHECK(Status IN ('Borrowed', 'Returned')) NOT NULL DEFAULT 'Borrowed',
    FOREIGN KEY (BookID) REFERENCES Books(BookID) ON DELETE CASCADE,
    FOREIGN KEY (MemberID) REFERENCES Members(MemberID) ON DELETE CASCADE
);

